name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: Run tests
        run: make test

      - name: Install go-test-coverage
        run: go install github.com/vladopajic/go-test-coverage/v2@latest

      - name: Check coverage
        run: make coverage-check
